spring.application.name=clinic-bot
server.port=8090

bot.name=VetClinicBot
bot.token=${BOT_TOKEN:7837490236:AAFYka05fv1LDRseAdcJ3E_n_GxiGI3pOtA}
bot.path=/webhook
bot.webhook.url=${BOT_WEBHOOK_URL:https://jpr3ta-109-174-76-92.ru.tuna.am}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/vet-clinic
spring.datasource.schema=telegram
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:changelogs/changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.default-schema=telegram
#spring.liquibase.drop-first=true

jetty.baseUrl=http://${JETTY_HOST:localhost}:${JETTY_PORT:9091}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/clinic-realm}
spring.security.oauth2.client.registration.telegram-bot.client-id=telegram-bot-service
spring.security.oauth2.client.registration.telegram-bot.client-secret=${KEYCLOAK_CLIENT_SECRET:MnRm2WcQMWruSA09qH2jpL9dwwF45ijx}
spring.security.oauth2.client.registration.telegram-bot.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.telegram-bot.provider=keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/clinic-realm}

mqtt.broker=tcp://${MQTT_HOST:localhost}:${MQTT_PORT:1883}
mqtt.client-id=pet-analyzer-client
mqtt.topic=pet/anomalies

gateway.url=http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8888}
service.appointment.name=appointment-service
service.appointment.url=${gateway.url}/api/appointment/tgUser/{tgUserId}
service.profile.name=profile-service
service.profile.url=${gateway.url}/api/profile/owner/tg-chat-id