spring.application.name=clinic-bot
server.port=8090

bot.name=VetClinicBot
bot.token=7837490236:AAFYka05fv1LDRseAdcJ3E_n_GxiGI3pOtA
bot.path=/webhook
bot.webhook.url=https://fr3hdn-178-47-3-244.ru.tuna.am

spring.datasource.url=jdbc:postgresql://localhost:5433/vet-clinic
spring.datasource.schema=telegram
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:changelogs/changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.drop-first=true

jetty.baseUrl=http://localhost:9091

clients.appointment.name=appointment-service
clients.appointment.baseUrl=http://localhost:8081
clients.appointment.getUrl=/appointment/{tgUserId}